@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AbstractRepository<ID, E>
class CategorieBautura
class CategorieBauturaService
class CsvExporter
class DailyReportService
class DrinkShopApp
class DrinkShopController
class DrinkShopService
class FileAbstractRepository<ID, E>
class FileCategorieBauturaRepository
class FileOrderRepository
class FileProductRepository
class FileRetetaRepository
class FileStocRepository
class FileTipBauturaRepository
class IngredientReteta
class Order
class OrderItem
class OrderItemValidator
class OrderService
class OrderValidator
class Product
class ProductService
class ProductTest
class ProductValidator
class ReceiptGenerator
interface Repository<ID, E> << interface >>
class RepositoryException
class Reteta
class RetetaService
class RetetaValidator
class Stoc
class StocService
class StocValidator
class TipBautura
class TipBauturaService
class ValidationException
interface Validator<T> << interface >>

AbstractRepository              -[#008200,dashed]-^  Repository                     
CategorieBauturaService        "1" *-[#595959,plain]-> "repo\n1" Repository                     
DailyReportService             "1" *-[#595959,plain]-> "repo\n1" Repository                     
DrinkShopController            "1" *-[#595959,plain]-> "categorieList\n*" CategorieBautura               
DrinkShopController            "1" *-[#595959,plain]-> "service\n1" DrinkShopService               
DrinkShopController            "1" *-[#595959,plain]-> "newRetetaList\n*" IngredientReteta               
DrinkShopController            "1" *-[#595959,plain]-> "currentOrder\n1" Order                          
DrinkShopController            "1" *-[#595959,plain]-> "currentOrderItems\n*" OrderItem                      
DrinkShopController            "1" *-[#595959,plain]-> "productList\n*" Product                        
DrinkShopController            "1" *-[#595959,plain]-> "retetaList\n*" Reteta                         
DrinkShopController            "1" *-[#595959,plain]-> "tipList\n*" TipBautura                     
DrinkShopService               "1" *-[#595959,plain]-> "categorieBauturaService\n1" CategorieBauturaService        
DrinkShopService               "1" *-[#595959,plain]-> "report\n1" DailyReportService             
DrinkShopService               "1" *-[#595959,plain]-> "orderService\n1" OrderService                   
DrinkShopService               "1" *-[#595959,plain]-> "productService\n1" ProductService                 
DrinkShopService               "1" *-[#595959,plain]-> "retetaService\n1" RetetaService                  
DrinkShopService               "1" *-[#595959,plain]-> "stocService\n1" StocService                    
DrinkShopService               "1" *-[#595959,plain]-> "tipBauturaService\n1" TipBauturaService              
FileAbstractRepository          -[#000082,plain]-^  AbstractRepository             
FileCategorieBauturaRepository  -[#000082,plain]-^  FileAbstractRepository         
FileOrderRepository             -[#000082,plain]-^  FileAbstractRepository         
FileOrderRepository            "1" *-[#595959,plain]-> "productRepository\n1" Repository                     
FileProductRepository           -[#000082,plain]-^  FileAbstractRepository         
FileRetetaRepository            -[#000082,plain]-^  FileAbstractRepository         
FileRetetaRepository           "1" *-[#595959,plain]-> "productRepo\n1" Repository                     
FileStocRepository              -[#000082,plain]-^  FileAbstractRepository         
FileTipBauturaRepository        -[#000082,plain]-^  FileAbstractRepository         
Order                          "1" *-[#595959,plain]-> "items\n*" OrderItem                      
OrderItem                      "1" *-[#595959,plain]-> "product\n1" Product                        
OrderItemValidator              -[#008200,dashed]-^  Validator                      
OrderService                   "1" *-[#595959,plain]-> "orderRepo\n1" Repository                     
OrderService                   "1" *-[#595959,plain]-> "validator\n1" Validator                      
OrderValidator                 "1" *-[#595959,plain]-> "itemValidator\n1" OrderItemValidator             
OrderValidator                  -[#008200,dashed]-^  Validator                      
ProductService                 "1" *-[#595959,plain]-> "productRepo\n1" Repository                     
ProductService                 "1" *-[#595959,plain]-> "validator\n1" Validator                      
ProductTest                     -[#595959,dashed]->  Product                        : "«create»"
ProductTest                    "1" *-[#595959,plain]-> "product\n1" Product                        
ProductValidator                -[#008200,dashed]-^  Validator                      
Reteta                         "1" *-[#595959,plain]-> "ingrediente\n*" IngredientReteta               
Reteta                         "1" *-[#595959,plain]-> "product\n1" Product                        
RetetaService                  "1" *-[#595959,plain]-> "retetaRepo\n1" Repository                     
RetetaService                  "1" *-[#595959,plain]-> "validator\n1" Validator                      
RetetaValidator                 -[#008200,dashed]-^  Validator                      
StocService                    "1" *-[#595959,plain]-> "stocRepo\n1" Repository                     
StocService                    "1" *-[#595959,plain]-> "validator\n1" Validator                      
StocValidator                   -[#008200,dashed]-^  Validator                      
TipBauturaService              "1" *-[#595959,plain]-> "repo\n1" Repository                     
@enduml
